# Generated by Django 3.1.4 on 2020-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image_url',
        ),
        migrations.AddField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='', upload_to='destinations'),
            preserve_default=False,
        ),
    ]
