# Generated by Django 3.1.4 on 2020-12-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_auto_20201208_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='user',
        ),
    ]
